require("dotenv").config();
const fs = require("fs");
const path = require("path");
const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { resume, selfDescription, jobDescription } = require("./src/services/temp");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
});

async function run() {
    try {
        console.log("Generating original resume HTML...");
        const prompt = `Generate resume for a candidate with the following details:
                            Resume: ${resume()}
                            Self Description: ${selfDescription()}
                            Job Description: ${jobDescription()}

                            the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                            The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                            The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                            you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                            The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                            The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                        `

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: resumePdfSchema.toJSONSchema(),
            }
        });
        
        const jsonContent = JSON.parse(response.text);
        const outputPath = path.join(__dirname, "resume_original.html");
        fs.writeFileSync(outputPath, jsonContent.html);
        console.log("Original resume HTML saved to:", outputPath);
        
    } catch (err) {
        console.error("HTML generation failed:", err);
    }
}

run();
